model_settings:
  embedding_model: "paraphrase-multilingual-MiniLM-L12-v2"
  similarity_threshold: 0.65

knowledge_base:
  path: "./knowledge_base"
  allowed_extensions: [".pdf", ".txt", ".md"]
  default_responses:
    - "Bunu tam anlayamadım. Detaylı bir şekilde tekrardan yazar mısın?"

response_settings:
  enhanced_app_template: |
    <div class="app-detail">
      <h4>Bera Şirketi Chatbot Projesi</h4>
      <p>Bu proje derin öğrenme ve rag ile yapılmıştır</p>
      <a href="{url}" class="app-link">Detayları Görüntüle</a>
    </div>